services:
  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - ray-network

  head-node:
    build: ./head_node
    restart: always
    ports:
      - "5001:5000"  # Flask API
      - "8265:8265"  # Ray Dashboard
      - "10001:10001"  # Ray client server port (instead of 6379)
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_IP=143.110.246.120
      - RAY_REDIS_PASSWORD=5241590000000000
    volumes:
      - head_node_logs:/app/logs
    networks:
      - ray-network

networks:
  ray-network:
    driver: bridge

volumes:
  redis_data:
  head_node_logs: 